name: RankUp
main: rankup\RankUp
description: "A prison rankup plugin for MagmaPrison."
version: 1.0
author: Falkirks, iiFlamiinBlaze
api: [3.0.0-ALPHA7]
load: POSTWORLD
softdepend: ["EconomyAPI", "PocketMoney", "PurePerms"]
permissions:
 rankup:
  default: true
  children:
    rankup.rankup:
      default: true
      description: Allow ranking up
    rankup.admin:
      default: op
      description: Manage RankUp and view statistics
    rankup.groups:
      default: false
      description: Do NOT set this. It is used for group managment.
